### ISSUE TITLE
l10n-tw 的代表 logo

### ISSUE THREAD

**Issue by zerng07** [l10n-tw/l10n-tw.github.io#2]
嗨，大家好！

我們誠徵 l10n-tw 的代表 logo。
## 我們是誰

l10n-tw，即 L10n Taiwan 社群，主要宗旨為協助任何自由與開源軟體專案，使其對正體中文（繁體中文）使用者變得更好用、更方便、更友善。
## 圖片規格
1. 小圖，縮圖用，建議 PNG 格式，至少提供 16x16 一份。
2. 大圖，一般用，建議 SVG 格式。
   當給了我們 logo 圖後，代表你同意給我們使用、修改與散布該 logo 圖。
   所以上傳前請確定你已知曉並願意接受喔。
## 使用情境

可能的使用情境包括 l10n-tw 之 github 大頭、telegram 頻道圖、相關社群活動上可能會拿來用… 等。

只要不少 l10n-tw 參與者都覺得不錯就會換上使用！

**Comment by s8321414** [comment]
XD

**Comment by Vdragon** [comment]
隨便拿 Inkscape 來湊湊
![l10n-tw-logo-taiwan svg](https://cloud.githubusercontent.com/assets/1192163/16540094/2db10e38-408a-11e6-830f-1d5904264779.png)

## 特色
- 字型選用思源黑體 TW
- 包含台澎琉蘭綠、不包含金馬
- 來源碼為 Inkscape SVG

**Comment by Vdragon** [comment]
已建立新 repo
https://github.com/l10n-tw/l10n-tw-logo

**Comment by zerng07** [comment]
OK, 就先用這個吧～ 結案！

如果有更好的設計，請提出，再開 issue 囉～
