### ISSUE TITLE
網站缺一個 https://github.com/l10n-tw 的連結

### ISSUE THREAD

**Issue by Artoria2e5** [l10n-tw/l10n-tw.github.io#7]
感覺網站上沒有社羣 GitHub 的連結很奇怪……大概可以在右上角加一個「Fork me on GitHub」？（中文怎麼講？）

**Comment by chiyi4488** [comment]
@Artoria2e5 我加在了翻譯頁面了
https://github.com/l10n-tw/l10n-tw.github.io/pull/8

**Comment by chiyi4488** [comment]
Merged ( #8 )
